### 문자 데이터
* 문자형 데이터
    - 사이킷런은 문자열 값을 입력 값으로 처리 하지 않기 때문에 숫자 형으로 변환해야 한다.

#### LabelEncder
- 문자를 숫자로 변환해주는 기능
- .fit(값) : 변경하고자 하는 문자열 등록 기능
- .transform(값) : fit으로 등록한 문자열을 적용해준다
- .fit_transform : fit과 transform의 두가지 기능을 합친 기능
- .inverse_transform(값) : 변환된 숫자를 원래 값(문자)으로 표현해준다
- .classes_ : 숫자로 변환된 문자를 표현해 준다. 표현된 값은 0번째 번호부터 순차적으로 나오게 된다
---

In [25]:
import pandas as pd
df = pd.read_csv("../../data_set/2.데이터 클린징/test2.csv")
df

     name   color
0   apple     red
1  banana  yellow
2  cherry     red
3  durian   green

In [26]:
df.T

           0       1       2       3
name   apple  banana  cherry  durian
color    red  yellow     red   green

In [2]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le = LabelEncoder()
le.fit( df['name'] )
df['name'] = le.transform(df['name'])
df

   name   color
0     0     red
1     1  yellow
2     2     red
3     3   green

In [5]:
df['color-1'] = le.fit_transform(df['color'])
df

   name   color  color-1
0     0     red        1
1     1  yellow        2
2     2     red        1
3     3   green        0

In [7]:
print( df['color'].unique() )
df['color-1'].unique()

['red' 'yellow' 'green']

array([1, 2, 0])

In [9]:
items = {'red':111, 'yellow':2222,'green':333 }
df['color_num'] = df['color'].map( items )
df

   name   color  color-1  color_num
0     0     red        1        111
1     1  yellow        2       2222
2     2     red        1        111
3     3   green        0        333

In [10]:
df=pd.DataFrame({
    'id':[302,504,708,103,343,565],
    'name':['Watch','Camera','Phone','Shoes','Laptop','Bed'],
    'cost':["300","400","350","100","1000","400"],
    'flt':["30.1","40.1","35.1","10.1","10.1","40.1"]
    
})
df

    id    name  cost   flt
0  302   Watch   300  30.1
1  504  Camera   400  40.1
2  708   Phone   350  35.1
3  103   Shoes   100  10.1
4  343  Laptop  1000  10.1
5  565     Bed   400  40.1

In [11]:
df_copy = df.copy()

In [12]:
df_copy.dtypes

id       int64
name    object
cost    object
flt     object
dtype: object

In [13]:
df_copy['cost'] = pd.to_numeric( df_copy['cost'] )
df_copy.dtypes

id       int64
name    object
cost     int64
flt     object
dtype: object

In [14]:
df_copy['flt'] = pd.to_numeric( df_copy['flt'] )
df_copy.dtypes

id        int64
name     object
cost      int64
flt     float64
dtype: object

#### astype
- 열의 요소의 type를 변경하는 기능
---

In [15]:
df_copy = df.copy()
df_copy.dtypes

id       int64
name    object
cost    object
flt     object
dtype: object

In [16]:
df_copy['cost'] = df_copy['cost'].astype(int)
df_copy['flt'] = df_copy['flt'].astype(float)
df_copy.dtypes

id        int64
name     object
cost      int64
flt     float64
dtype: object

#### apply
- 여러 값들은 한번에 변경

In [17]:
df_copy = df.copy()
df_copy.dtypes

id       int64
name    object
cost    object
flt     object
dtype: object

In [18]:
df_copy[['flt','cost']] = df_copy[['flt','cost']].apply( pd.to_numeric )
df_copy.dtypes

id        int64
name     object
cost      int64
flt     float64
dtype: object

In [19]:
data = {'A':[1, 2, 3],  'B':[4, 5, 6], 'C':[7, 8, 9] }
df = pd.DataFrame(data)
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [20]:
df['A'].sum()

np.int64(6)

In [21]:
import numpy as np
np.sum( df['A'] )

np.int64(6)

In [22]:
df.sum()

A     6
B    15
C    24
dtype: int64

In [23]:
df.apply( np.sum )

A     6
B    15
C    24
dtype: int64