### 과대적합과 과소적합
#### 과대적합(overfitting)
* 훈련데이터에만 잘 맞고 테스트데이터에는 낮은 정답률이 나오는 경우

#### 과소적합(underfitting)
* 훈련이 제대로 이루어지지 않아 테스트 데이터보다 훈련데이터의 정답률이 낮은 경우
* 훈련, 테스트데이터 모두 정답률이 낮은 경우
* 훈련데이터의 개수가 적을 경우

---

### 스케일링
* 수치형 데이터들의 값의 범위가 클 경우 사용한다.(연산 속도 증가)
    - 예를 들어 주식의 가격을 생각했을 경우 100원의 1%와 100000원의 1%를 계산하고자 한다면 같은 1%연산이지만 숫자가 클 경우 연산속도에 영향을 미치게 된다.
* 서로 다른 변수의 값 범위를 일정한 수준으로 맞추고자 하는 경우
* 대표적 스케일링 클래스는 StandardScaler, MinMaxScaler이 있다
* 사용 이유
    - 연산속도를 올릴 수 있다
    - 확률을 높일 수 있다
    - 과대, 과소적합을 조금은 해결할 수 있다
* 참고
    - 이상치가 있을 경우 범위의 차이가 커지게 되므로 이상치는 제거해야 한다
    - RandomForest는 따로 스케일링 할 필요가 없다.(tree계열은 따로 스케일 할 필요가 없다)

#### StandardScaler(label값은 스케일 하지 않는다)
* 사이킷런에서 서포트벡터머신, 선형회귀, 로지스틱 회귀에 적용하는 것이 예측 성능 향상에 중요한 요소가 된다.
* 각 특성의 평균을 0, 편차를 1에 가깝게 변경하여 정규분포로 만드는 것이다

#### MinMaxScaler(label값은 스케일 하지 않는다)
* 모든 특성이 정확하게 0과 1사이에 위치하도록 데이터를 변경
* k-means, k-nearest neighbor등의 알고리즘에 좋은 성능을 보인다

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [3]:
movie = {'daum':[2,4,6,8,10], "naver":[1,2,3,4,5]}
mv = pd.DataFrame( movie )
mv

   daum  naver
0     2      1
1     4      2
2     6      3
3     8      4
4    10      5

In [5]:
min_max_scaler = MinMaxScaler()
tr = min_max_scaler.fit_transform( mv )
pd.DataFrame(tr, columns=['daum','naver'])

   daum  naver
0  0.00   0.00
1  0.25   0.25
2  0.50   0.50
3  0.75   0.75
4  1.00   1.00

In [6]:
mv

   daum  naver
0     2      1
1     4      2
2     6      3
3     8      4
4    10      5

In [7]:
mv.describe()

            daum     naver
count   5.000000  5.000000
mean    6.000000  3.000000
std     3.162278  1.581139
min     2.000000  1.000000
25%     4.000000  2.000000
50%     6.000000  3.000000
75%     8.000000  4.000000
max    10.000000  5.000000

In [9]:
standard_scaler = StandardScaler()
scaler = standard_scaler.fit_transform(mv)
scaler
df_sc = pd.DataFrame( scaler, columns=['daum','naver'] )
df_sc

       daum     naver
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

In [12]:
df_sc.describe()

           daum     naver
count  5.000000  5.000000
mean   0.000000  0.000000
std    1.118034  1.118034
min   -1.414214 -1.414214
25%   -0.707107 -0.707107
50%    0.000000  0.000000
75%    0.707107  0.707107
max    1.414214  1.414214

In [13]:
df = pd.read_csv("../data_set/5.스케일링/bank_train_clean.csv")
df.head(3)

   age  duration  campaign  pdays  previous  y
0   58       261         1     -1         0  0
1   44       151         1     -1         0  0
2   33        76         1     -1         0  0

In [14]:
df.columns

Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'y'], dtype='object')

In [15]:
f = ['age', 'duration', 'campaign', 'pdays', 'previous']
label = 'y'
X, y = df[f], df[label]

In [18]:
X.head(1)

   age  duration  campaign  pdays  previous
0   58       261         1     -1         0

In [20]:
X.shape, y.shape

((45211, 5), (45211,))

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [23]:
X_train.shape, X_test.shape

((31647, 5), (13564, 5))

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
rfc = RandomForestClassifier()
rfc.fit( X_train, y_train )
print("학습 데이터 score : ", rfc.score(X_train, y_train) )
print("test 데이터 score : ", rfc.score(X_test, y_test) )
f"과적합 확인 : {rfc.score(X_train, y_train) - rfc.score(X_test, y_test) } "

학습 데이터 score :  0.9912787941985022
test 데이터 score :  0.8815983485697434

'과적합 확인 : 0.10968044562875878 '

In [29]:
X_train.head(1)

      age  duration  campaign  pdays  previous
9992   38       553         2     -1         0

In [31]:
scaler = StandardScaler()
scaler.fit( X_train )

X_train_scaler = scaler.transform( X_train )
X_test_scaler = scaler.transform( X_test )

X_train_scaler

array([[-0.27335616,  1.15073773, -0.24450797, -0.41071141, -0.23484895],
       [-1.30968572,  0.34028856, -0.56623861, -0.41071141, -0.23484895],
       [-1.49810927,  1.3611428 , -0.56623861,  3.06268562,  1.39387287],
       ...,
       [ 1.13982051, -0.7117368 ,  0.72068396, -0.41071141, -0.23484895],
       [ 0.38612629,  1.19749441, -0.24450797, -0.41071141, -0.23484895],
       [-1.21547394, -0.4311967 , -0.56623861,  0.50545998,  0.1723315 ]],
      shape=(31647, 5))

In [32]:
rfc.fit( X_train_scaler, y_train )
print("학습 데이터 score : ", rfc.score(X_train_scaler, y_train) )
print("test 데이터 score : ", rfc.score(X_test_scaler, y_test) )
f"과적합 확인 : {rfc.score(X_train_scaler, y_train) - rfc.score(X_test_scaler, y_test) } "

학습 데이터 score :  0.991152399911524
test 데이터 score :  0.8813771748746683

'과적합 확인 : 0.10977522503685577 '

In [33]:
scaler = MinMaxScaler()
scaler.fit( X_train )
X_train_scaler = scaler.transform( X_train )
X_test_scaler = scaler.transform( X_test )

rfc.fit( X_train_scaler , y_train )

print("학습 데이터 score : ", rfc.score(X_train_scaler, y_train) )
print("test 데이터 score : ", rfc.score(X_test_scaler, y_test) )
f"과적합 확인 : {rfc.score(X_train_scaler, y_train) - rfc.score(X_test_scaler, y_test) } "

학습 데이터 score :  0.9912787941985022
test 데이터 score :  0.8783544677086406

'과적합 확인 : 0.11292432648986162 '