### 사과 품질 분류하기
* 컬럼
    - Size : 크기
    - Weight : 무게
    - Sweetness : 단맛
    - Crunchiness : 아삭한 정도
    - Juiciness : 사과 즙의 정도
    - Ripeness : 사과의 숙성 정도
    - Acidity : 신맛
    - Quality : 품질

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data_set/4.분류/apple_quality.csv")
df.head()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good

In [3]:
df['Quality'].unique()

array(['good', 'bad', nan], dtype=object)

In [4]:
df.isnull().sum()

A_id           1
Size           1
Weight         1
Sweetness      1
Crunchiness    1
Juiciness      1
Ripeness       1
Acidity        0
Quality        1
dtype: int64

In [5]:
df.shape

(4001, 9)

In [6]:
df.dropna( axis=0, inplace=True)

In [7]:
df.shape

(4000, 9)

In [8]:
df.isnull().sum()

A_id           0
Size           0
Weight         0
Sweetness      0
Crunchiness    0
Juiciness      0
Ripeness       0
Acidity        0
Quality        0
dtype: int64

In [9]:
df.columns

Index(['A_id', 'Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness',
       'Ripeness', 'Acidity', 'Quality'],
      dtype='object')

In [10]:
df.head(1)

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.34633,-1.012009,1.8449,0.32984,-0.491590483,good

In [14]:
features = ['Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness',
       'Ripeness', 'Acidity']
label = 'Quality'
X, y = df[features] , df[label]
X.head(3) , y

(       Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
 0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840
 1 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530
 2 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033

         Acidity
 0  -0.491590483
 1  -0.722809367
 2   2.621636473  ,
 0       good
 1       good
 2        bad
 3       good
 4       good
         ...
 3995     bad
 3996    good
 3997     bad
 3998    good
 3999    good
 Name: Quality, Length: 4000, dtype: object)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [18]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2800, 7), (2800,), (1200, 7), (1200,))

### 모델 생성 및 학습, 평가

#### Kneighbors(K-최근접 이웃 알고리즘)
* 주위의 가장 가까운 다른 데이터를 보고 현재 데이터를 판단
* 기본 비교 개수는 5개로 되어 있다
* 비교 개수를 변경하고자 할 경우 n_neighbors에 값 지정

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
kn = KNeighborsClassifier() #모델생성
kn.fit( X_train, y_train ) #학습
kn.score( X_test, y_test )

0.9066666666666666

#### SVM(Support Vector Machine)
* 특정 데이터들을 구분하는 선을 찾고, 이를 기반으로 패턴을 인식하는 방법
* kernel : linear, rbf
* linear : 선형으로 데이터들을 구분지을 수 있는 경우. 즉, 데이터 분포가 균일 적인 경우
* rbf : 선형으로 데이터를 구분지을 수 없는 경우. 즉, 데이터 분포가 복잡한 경우

In [24]:
import sklearn.svm as svm

In [25]:
svm_linear = svm.SVC(kernel='linear')
svm_linear.fit(X_train, y_train)
svm_linear.score(X_test, y_test)

0.7608333333333334